# 本地跑测试用
version: "3"
services:
  speech-test:
    container_name: speech-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./log:/usr/src/app/log:rw
      - ./result:/usr/src/app/result:rw
      - ./report:/usr/src/app/report:rw